name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      test-command: |
        env TEST_LANG="c" NIMFLAGS="${NIMFLAGS} --mm:refc" nim c ./tests/test_all
        ./tests/test_all
        env TEST_LANG="cpp" NIMFLAGS="${NIMFLAGS} --mm:refc" nim c ./tests/test_all
        ./tests/test_all
        env TEST_LANG="c" NIMFLAGS="${NIMFLAGS} --mm:orc" nim c ./tests/test_all
        ./tests/test_all
        env TEST_LANG="cpp" NIMFLAGS="${NIMFLAGS} --mm:orc" nim c ./tests/test_all
        ./tests/test_all
